max_width = 100
tab_spaces = 2
single_line_if_else_max_width = 100
chain_one_line_max = 70

control_style = "Legacy"
fn_args_density = "Compressed"
fn_single_line = true
array_layout = "Visual"
chain_indent = "Visual"
fn_args_layout = "Visual"
struct_lit_style = "Visual"
where_pred_indent = "Visual"